# Setup
title: PoignardAzur
tagline: Developer blog of Olivier Faure
url: https://poignardazur.github.io/
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-inline-svg


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Olivier Faure
  url: https://poignardazur.github.io/
  email: olivier.cj.faure@gmail.com

# Custom vars
version: 3.0.0
